apiVersion: v1
# jenis Kind PersistentVolume
kind: PersistentVolume
metadata:
  # atur nama/identifier PersistentVolume
  name: mongo-pv
  labels:
    type: local
  namespace: submisi
spec:
  # jabarkan kebutuhan PV berkapasitas 1Gi
  # dengan akses ReadWriteOnce
  # dengan host path di /data/db
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/db"
---
apiVersion: v1
# jenis Kind PersistentVolumeClaim untuk klaim PV yg sudah dibuat
kind: PersistentVolumeClaim
metadata:
  # atur nama/identifier PVC
  name: mongo-pv-claim
  labels:
    app: mongo
  namespace: submisi
spec:
  # jabarkan kebutuhan klaim PV berkapasitas 1Gi
  # dengan akses ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
