apiVersion: v1
# jenis Kind Service
kind: Service
metadata:
  # atur metadata name, namespace & labels
  name: mongo
  namespace: submisi
  labels:
    app: mongo
spec:
  selector:
    # buat selector Service
    app: mongo
    tier: backend
  ports:
    - port: 27017
  # jenis clusterIP None karena sebuah Headless Service
  # backend memanfaatkan Service DNS name, akses service menggunakan selector mongo
  clusterIP: None
