apiVersion: v1
# jenis Kind Secret menyimpan data privat/secret
kind: Secret
metadata:
  # atur nama/identifier Secret
  name: mongo-secret
  namespace: submisi
type: Opaque
data:
  # dari tips submisi, isi MONGO_ROOT_USERNAME dengan admin dan MONGO_ROOT_PASSWORD
  # dengan supersecretpassword dalam bentuk base64.
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
