apiVersion: v1
# jenis Kind Service
kind: Service
metadata:
  # atur metadata name, namespace & labels
  name: karsajobs
  namespace: submisi
  labels:
    app: karsajobs
    tier: backend
spec:
  selector:
    # buat selector Service
    app: karsajobs
    tier: backend
  # jenis NodePort agar bisa diakses di luar cluster
  type: NodePort
  ports:
  # expose port app backend ke 8080 sesuai Dockerfile
  - port: 8080
    targetPort: 8080
    nodePort: 30080
