apiVersion: apps/v1
# jenis Kind Deployment
kind: Deployment
metadata:
  # atur metadata name, namespace & labels
  name: karsajobs-ui
  namespace: submisi
  labels:
    app: karsajobs-ui
    tier: frontend
spec:
  selector:
    matchLabels:
      # atur selector Service
      app: karsajobs-ui
  replicas: 1
  template:
    metadata:
      # atur metadata labels
      labels:
        app: karsajobs-ui
        tier: frontend
    spec:
      containers:
      - name: karsajobs-ui
        # atur image dari Github registry yang sudah di-build
        image: ghcr.io/theoyrus/karsajobs-ui:latest
        # opsional apabila tidak ingin pull ulang, jika sudah di-pull di minikube
        # imagePullPolicy: Never
        env:
          # atur environment variabel koneksi ke backend
          - name: VUE_APP_BACKEND
            # diambil dari Tips Submission
            # Ketika hendak deploy karsajobs-ui (frontend), 
            # pastikan Anda mengubah nilai VUE_APP_BACKEND yang ada di berkas .env 
            # dengan nilai Node IP dan Node Port sesuai pada komputer Anda.

            # value: http://$(KARSAJOBS_SERVICE_HOST):$(KARSAJOBS_SERVICE_PORT)
            value: http://192.168.49.2:30080
            # value diatas merupakan nilai ip node (execute: minikube ip) untuk keperluan test akses di browser localhost
        ports:
        # expose port app frontend
        - containerPort: 80
