apiVersion: v1
# jenis Kind Service
kind: Service
metadata:
  # atur metadata name, namespace & labels
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
  namespace: submisi
spec:
  selector:
    # buat selector Service
    app: karsajobs-ui
    tier: frontend
  type: NodePort
  # jenis NodePort agar bisa diakses di luar cluster
  ports:
  # expose port app backend ke 8000 sesuai Dockerfile
  - port: 8000
    targetPort: 8000
    nodePort: 30081
